[package]
name = "dataplane-k8s-sample-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["derive", "parsing", "proc-macro", "full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
schemars = { workspace = true, features = ["derive", "std"] }
