["ninja-1.13.2"]
cve = "CVE-2021-4336"

["libsndfile-1.2.2"]
cve = [ "CVE-2024-50612", "CVE-2024-50613", "CVE-2025-52194" ]

["tokio-1.47.1"]
cve = "CVE-2024-27308"

["idna-0.5.0"]
cve = "CVE-2024-12224"

["diff-0.1.13"]
cve = "CVE-2024-13278"

["gnupg-2.4.8"]
cve = [ "CVE-2025-68972", "CVE-2025-68973" ]

["orc-0.4.41"]
cve = "CVE-2025-47436"

[fontforge-20251009]
cve = [ "CVE-2025-15276", "CVE-2025-15277", "CVE-2025-15278", "CVE-2025-15279" ]

["go-1.25.5"]
cve = "CVE-2023-49292"

["sassc-3.6.2"]
cve = "CVE-2022-43357"

["quote-1.0.37"]
cve = "CVE-2020-16194"

["hyper-1.6.0"]
cve = [ "CVE-2024-23741", "CVE-2025-7074" ]

["mercurial-7.1-vendor"]
cve = "CVE-2022-43410"

["dash-0.5.13.1"]
cve = "CVE-2024-21485"

["avahi-0.8"]
cve = "CVE-2021-26720"

["home-0.5.9"]
cve = [ "CVE-2021-25264", "CVE-2023-3612", "CVE-2024-52327", "CVE-2024-52329" ]

["zlib-1.3.1"]
cve = "CVE-2023-6992"

["quote-1.0.40"]
cve = "CVE-2020-16194"

["glibc-2.40-66"]
cve = [ "CVE-2025-5702", "CVE-2025-5745" ]

["go-1.22.12-linux-amd64-bootstrap"]
cve = [ "CVE-2023-49292", "CVE-2025-0913", "CVE-2025-61727", "CVE-2025-61729" ]

["mercurial-7.1"]
cve = "CVE-2022-43410"

["libmicrohttpd-1.0.2"]
cve = [ "CVE-2025-59777", "CVE-2025-62689" ]

["openexr-3.3.5"]
cve = [ "CVE-2025-64181", "CVE-2025-64182", "CVE-2025-64183" ]

["yasm-1.3.0"]
cve = [ "CVE-2021-33454", "CVE-2021-33455", "CVE-2021-33456", "CVE-2021-33457", "CVE-2021-33458", "CVE-2021-33459", "CVE-2021-33460", "CVE-2021-33461", "CVE-2021-33462", "CVE-2021-33463", "CVE-2021-33464", "CVE-2021-33465", "CVE-2021-33466", "CVE-2021-33467", "CVE-2021-33468", "CVE-2023-30402", "CVE-2023-31972", "CVE-2023-31973", "CVE-2023-31974", "CVE-2023-31975", "CVE-2023-51258" ]

["cups-2.4.16"]
cve = "CVE-2022-26691"

["libmpeg2-0.5.1"]
cve = "CVE-2022-37416"

["http-1.1.0"]
cve = [ "CVE-2022-36032", "CVE-2023-26044" ]

["giflib-5.2.2"]
cve = "CVE-2024-45993"

["curl-0.4.46"]
cve = [ "CVE-2020-8284", "CVE-2022-27776", "CVE-2022-27781", "CVE-2022-27782", "CVE-2022-32206", "CVE-2022-32221", "CVE-2022-35252", "CVE-2022-43552", "CVE-2023-28319", "CVE-2023-28320", "CVE-2023-28321", "CVE-2023-28322" ]

["audiofile-0.3.6"]
cve = "CVE-2020-18781"

["gcc-15.2.0"]
cve = "CVE-2023-4039"

["http-0.2.12"]
cve = "CVE-2020-35669"

["subversion-1.14.5"]
cve = [ "CVE-2020-2111", "CVE-2020-2304", "CVE-2021-21698", "CVE-2022-29046", "CVE-2022-29048" ]

[lapack-3]
cve = "CVE-2021-4048"

["binutils-2.44"]
cve = [ "CVE-2025-1153", "CVE-2025-3198", "CVE-2025-8224", "CVE-2025-8225" ]

["quote-1.0.36"]
cve = "CVE-2020-16194"

["mercurial-7.1-vendor-staging"]
cve = "CVE-2022-43410"

["jbig2dec-0.20"]
cve = "CVE-2023-46361"

["rubygems-3.7.2"]
cve = "CVE-2022-36073"
