[toolchain]
# NOTE: you can and should manually update this on new rust releases
channel = "1.93.0"

components = [
  "rustc",
  "cargo",
  "rust-std",
  "rust-docs",
  "rustfmt",
  "clippy",
  "rust-analyzer",
  "rust-src",

  ## disabled components ##
  # "rust-mingw", # not relevant to us
  # "llvm-tools", # we already have a full llvm in the npins, no need for another
  # "miri", # not yet functional for us
  # "rustc-codegen-cranelift-preview" # not relevant to us
]

targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl"
]
