[toolchain]
# NOTE: you can and should manually update this on new rust releases
channel = "1.92.0"

components = [
  "rustc",
  "cargo",
  "rust-std",
  "rust-docs",
  "rustfmt-preview",
  "clippy",
  "rust-analyzer",
  "rust-src",
  # "llvm-tools"

  ## other (disabled) components ##
  # "rust-mingw", ## not relevant to us
  # "llvm-tools-preview", ## we already have a full llvm in the npins, no need for another
  # "rust-analysis", ## obsolete
  # "miri-preview", ## not yet functional for us
  # "rustc-codegen-cranelift-preview" ## not relevant to us
]

targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl"
]
