[package]
name = "dataplane-concurrency-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[features]
loom = []
shuttle = []
silence_clippy = []

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
