[package]
name = "dataplane-vpcmap"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[features]
default = []
bolero = ["dep:bolero", "net/bolero"]


[dependencies]
ahash = { workspace = true, features = ["no-rng"] }
bolero = { workspace = true, optional = true }
left-right = { workspace = true }
net = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
bolero = { workspace = true }
net = { workspace = true, features = ["bolero"] }
