[package]
name = "dataplane-pipeline"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
arc-swap = { workspace = true }
dyn-iter = { workspace = true }
id = { workspace = true }
linkme = { workspace = true }
net = { workspace = true, features = ["test_buffer"] }
ordermap = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tracectl = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
net = { workspace = true, features = ["test_buffer"] }
