[package]
name = "dataplane-left-right-tlcache"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
left-right = { workspace = true }
ahash = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
