[package]
name = "dataplane-tracectl"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
color-eyre = { workspace = true , features = [ "capture-spantrace", "color-spantrace", "tracing-error", "track-caller" ] }
linkme = { workspace = true }
ordermap = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true, features = ["traced-error"] }
tracing-subscriber = { workspace = true, features = ["registry", "std", "env-filter", "fmt"] }

[dev-dependencies]
serial_test = { workspace = true }
