[package]
name = "dataplane-k8s-sample-crds"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
k8s-intf = { workspace = true }

[build-dependencies]
k8s-intf = { workspace = true }