[package]
name = "dataplane-test-utils"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
caps = { workspace = true, default-features = false, features = [] }
nix = { workspace = true, default-features = false, features = ["sched", "fs"] }
rtnetlink = { workspace = true, default-features = false, features = ["tokio_socket"] }
tokio = { workspace = true, default-features = false, features = ["rt", "net", "time"] }
tracing = { workspace = true, default-features = false, features = [] }
