[package]
name = "dataplane-k8s-intf"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
# internal

# external
kube = { workspace = true, features = ["derive"] }
k8s-openapi = { workspace = true, features = ["latest", "schemars", "std"] }
schemars = { workspace = true, features = ["derive", "std"] }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
dotenvy = { workspace = true, features = [] }
ureq = { workspace = true, features = ["rustls", "gzip"] }
