[package]
name = "dataplane-concurrency"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[features]
loom = ["dep:loom", "concurrency-macros/loom"]
shuttle = ["dep:shuttle", "concurrency-macros/shuttle"]
silence_clippy = ["concurrency-macros/silence_clippy"] # Do not manually enable this feature, let --all-features do it for you

[dependencies]
loom = { workspace = true, optional = true, features = [] }
shuttle = { workspace = true, optional = true, features = [] }
concurrency-macros = { workspace = true, features = [] }
