[package]
name = "dataplane-k8s-types"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
kube = { workspace = true, features = ["derive"] }
kube-core = { workspace = true }
k8s-openapi = { workspace = true, features = ["latest", "schemars", "std"] }
schemars = { workspace = true, features = ["derive", "std"] }
serde = { workspace = true }
serde_json = { workspace = true }
