["CVE-2025-5702"]

package = "glibc"
description = """
The strcmp implementation optimized for the Power10 processor in the GNU C Library version 2.39 and later writes to vector registers v20 to v31 without saving contents from the caller (those registers are defined as non-volatile registers by the powerpc64le ABI), resulting in overwriting of its contents and potentially altering control flow of the caller, or leaking the input strings to the function to other parts of the program.
"""
note = """
we don't currently support Power10 so this does not apply to us
"""


["glibc-2.40-66"]
cve = [ "CVE-2025-5702", "CVE-2025-5745" ]

["gcc-15.2.0"]
cve = "CVE-2023-4039"

["binutils-2.44"]
cve = [ "CVE-2025-1153", "CVE-2025-3198", "CVE-2025-8224", "CVE-2025-8225" ]

["zlib-1.3.1"]
cve = "CVE-2023-6992"
