[package]
name = "dataplane-stats"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[features]
default = []
bolero = ["dep:bolero", "vpcmap/bolero", "net/bolero"]

[dependencies]
# internal
concurrency = { workspace = true }
net = { workspace = true }
pipeline = { workspace = true }
vpcmap = { workspace = true }

# external
arrayvec = { workspace = true }
bolero = { workspace = true, optional = true }
derive_builder = { workspace = true }
hashbrown = { workspace = true, features = ["default-hasher", "inline-more"] }
kanal = { workspace = true, features = ["async"] }
linkme = { workspace = true }
metrics = { workspace = true }
multi_index_map = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
serde = { workspace = true, features = ["derive"] }
small-map = { workspace = true, features = [] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "time", "sync"] }
tracectl = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
bolero = { workspace = true }
net = { workspace = true, features = ["bolero"] }
vpcmap = { workspace = true, features = ["bolero"] }
